services:
  tb:
    image: thingsboard/tb-postgres:latest
    container_name: tb-ce
    ports:
      - "8080:8080"   # UI/API HTTP
      - "1883:1883"   # MQTT
      - "5683-5688:5683-5688/udp" # CoAP opcional
    environment:
      TB_QUEUE_TYPE: in-memory
      HTTP_BIND_PORT: 8080
      MQTT_BIND_PORT: 1883
    volumes:
      - tb-data:/data
      - tb-logs:/var/log/thingsboard
    restart: unless-stopped
    networks:
      - tbnet
volumes:
  tb-data:
  tb-logs:
networks:
  tbnet:
    driver: bridge
