services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "1884:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    networks:
      - tbnet      # para que el gateway pueda resolverlo desde TB net
      - edgenet    # red de borde para devices locales

networks:
  tbnet:
    external: true
    name: cloud-thingsboard_tbnet
  edgenet:
    name: edge-net
